version: '3.8'

services:
  auth-api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/user-auth
      - JWT_SECRET=your-super-secret-jwt-key-here
      - JWT_EXPIRES_IN=24h
      - PORT=3000
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - auth-network

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=user-auth
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped
    networks:
      - auth-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - auth-network

volumes:
  mongo_data:
  redis_data:

networks:
  auth-network:
    driver: bridge
