export const ERROR_CODES = {
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  REGISTRATION_DISABLED: 'AUTH_REGISTRATION_DISABLED',
  EMAIL_TAKEN: 'AUTH_EMAIL_TAKEN',
  WEAK_PASSWORD: 'AUTH_WEAK_PASSWORD',
  ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  TWO_FACTOR_REQUIRED: 'AUTH_2FA_REQUIRED',
  INVALID_2FA_CODE: 'AUTH_INVALID_2FA_CODE',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
